services:
  - type: web
    name: app-client
    branch: main
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    buildFilter:
      paths:
        - client/**/*.js
      ignoredPaths:
        - client/**/*.test.js
  - type: web
    name: librarian-panel
    branch: main
    runtime: static
    rootDir: librarian-panel
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
  - type: web
    name: app-backend
    branch: main
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
